### ISSUE TITLE
500 when trying to assume non existing role

### ISSUE THREAD

**Issue by Raffo** [zalando-incubator/aws-credentials-service#10]
When trying to assume a role that doesn't exist (in this case, `PowerUser`) this is what I get: 

```
Traceback (most recent call last):
  File "/usr/local/bin/zaws", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/zalando_aws_cli/cli.py", line 331, in main
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/zalando_aws_cli/cli.py", line 105, in login
    credentials = get_aws_credentials(account_name, role_name, obj['service_url'])
  File "/usr/local/lib/python3.6/site-packages/zalando_aws_cli/cli.py", line 266, in get_aws_credentials
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://aws-credentials.stups.zalan.do/aws-accounts/ACCOUNT_NUMBER/roles/PowerUser/credentials
```

**Comment by hjacobs** [comment]
This should probably return a 403 instead:

```
 zhttp https://aws-credentials.example.org/aws-accounts/123123123123/roles/PowerUser/credentials
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 220
Content-Type: application/problem+json
Date: Mon, 23 Apr 2018 15:17:37 GMT
Server: Skipper

{
    "detail": "Failed to assume role: An error occurred (AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole",
    "status": 500,
    "title": "AWS Error",
    "type": "about:blank"
}
